project:
  type: website

website:
  title: "CA3 Data Analytics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: partA_sql.qmd
        text: Part A – SQL

format:
  html:
    theme: cosmo
    toc: true

